plugins:
  - react
  - functional

env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:functional/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  # no-shadow: 0
  # no-param-reassign: 0
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  react/jsx-no-constructed-context-values: 0
  react/no-unknown-property: 0
  functional/no-conditional-statements: 0
  functional/no-expression-statements: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statements: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  # import/no-extraneous-dependencies: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  testing-library/no-debug: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
